<head>
	<!-- styling for the footer section -->
	<style type="text/css">
		#footer_bar{position:fixed; height:40px; width:100%; bottom:0px; background-color: pink; background-size:cover; z-index: 900; margin-left: 0px; padding: 2px 0px 3px 0px;}
		#footer_bar div{position: relative; margin:0px auto; top:10px; height:90%; width:100%; z-index:inherit;}

		/* styling for the elements of the footer */
		#copywright_logo{}
		#aaruush_logo{background:url("images/webarch_logo.png") no-repeat/ 100% 100% transparent; height: 50px;width: 70px;float:right;}
		/* ends */
	</style>
</head>

<div id='footer_bar'>
	<div> 				 
		<div id='copywright_logo' class='footer_elements'> &copy;2013-14 WEBARCH-KONVOLVE'14-SRM University</div>
		<div id='webarch_logo' class='footer_elements f_logos'></div>
	</div>
</div>
