<head>
	<!-- styling sections -->

	<style type="text/css">
		#header_bar{width:1200px; height: 50px; background-color: #333;padding-top: 10px;padding-bottom: 10px; margin-top: -10px;}		


		/*logo styling*/
		#srm_logo{background:url("images/srm.png");background-size: 100% 100%;height: 50px;width: 100px;float:right;margin-top: 7px}
		#konvolve_logo{background: url("images/konvolve.png") no-repeat center center / 100% 100% transparent;height: 50px;width: 300px;
			float:left;}
		#aaruush_logo{background:url("images/aaruush.png") no-repeat center center / 100% 100% transparent;height: 50px;width: 70px;float:right;}
		.h_logos{}
		/* ends */
	</style>

	<!--  -->

</head>

<div id='header_bar'>
		<!-- elements of the header -->
		<div id='konvolve_logo' class='header_elements h_logos'> </div>
		<div id='srm_logo' class='header_elements h_logos'>	</div>

		<div id='aaruush_logo' class='header_elements h_logos'>	</div>
		<!--  -->
	
</div>