<head>
	<!-- styling for the footer section -->
	<style type="text/css">
		#footer_bar{position:fixed; height:40px; width:100%; bottom:0px; background-color: pink; z-index: 100; right:20px}
		#footer_bar>div{position: relative; margin:0px auto; top:10px; height:90%; width:1200px;}

		/* styling for the elements of the footer */
		#copywright_logo{}
		#webarch_logo{background:url("../imgs/webarch_logo.png") no-repeat center center / 100% 100% transparent;}
		/* ends */
	</style>
</head>

<!--<div id='footer_bar'>
	<div> 				 
		<div id='copywright_logo' class='footer_elements'> &copy;2013-14 WEBARCH-KONVOLVE'14-SRM University	</div>
		<div id='webarch_logo' class='footer_elements f_logos'>				</div>
	</div>
</div>
 -->