<head>
	<!-- styling for navigation bar section -->
	<style type="text/css">
		#nav_bar_wrapper{ height:25px; z-index: 99;
			background: #1D7F25;padding: 0.4%;font-size: 16px;}
		#nav_bar{position: relative;  display:block; margin:0px auto; height:100%; text-align: center;}
		.nav_links{padding-left:25px;padding-right: 25px;}
		/*styling for hyper links*/
		.nav_links a{text-decoration: none; color:#fff;font-size: 13px;}
		.nav_links a:link{text-decoration: none; color:#ccc;}
		.nav_links a:visited{text-decoration: none; color:#ccc;}
		.nav_links a:active{text-decoration: none; color:#ccc;}
		/*ends*/
		/*ends*/
	</style>
	<!--  -->
</head>

<div id='nav_bar_wrapper'>
	<div id='nav_bar'>
				<span id='home' class='nav_links'>		<a href="../index.php">HOME 			</a>	</span>		
				<span id='about' class='nav_links'>		<a href="./two.php">ABOUT 		</a>	</span>		
				<span id='themes' class='nav_links'> 	<a href="./themes.php"> THEMES 		</a>	</span>		
				<span id='rules' class='nav_links'> 	<a href="./three.php"> RULES		</a>	</span>			
	<!--			<span id='gallery' class='nav_links'>	<a href="../Theme/Gallery">GALLERY 	</a>	</span>		-->
				<span id='contact' class='nav_links'>	<a href="./contact.php">CONTACT 	</a> 	</span> 	
				<span id='abstract' class='nav_links'>	<a href="./register.php">ABSTRACT 	</a> 	</span> 	
				<span id='abstract' class='nav_links'>	<a href="./team.php">TEAM</a> 	</span> 	
				<span id='credits' class='nav_links'>	<a href="./credits.php">CREDITS 	</a> 	</span>	 	
			<!--  -->
	</div>
</div>
